site_name: "API Prime Magic Quadrants"
theme:
  name: material

nav:
  - Home: index.md
  - API Prime Magic Quadrants:
      - Service Implementation: main.md
      - Prime Numbers: prime-numbers.md
      - Arithmetic Sequence: arithmetic_sequence.md
      - Magic Quadrants: magic-quadrants.md
      - API Implementation: api-implementation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
